KEY = "Replace With Your API KEY"

BASE_URL = "Replace with Your API URL"

TAG_URL = BASE_URL + "/api/v1/extract/tags"

UPLOAD_URL = BASE_URL + "/api/v1/upload/file"

VALID_TAGS = ["CONTENT TYPE", "QUALITY", "GENRE", "GENRE SECONDARY", "BPM", "BPM ALT", "BPM VARIATION", "KEY", "KEY SECONDARY", "MOOD", "MOOD SECONDARY",
              "MOOD VALENCE", "ENERGY", "ENERGY VARIATION", "INSTRUMENTATION", "VOCAL PRESENCE", "VOCAL GENDER", "INSTRUMENT"]

TAGS = ["CONTENT TYPE", "GENRE", "BPM", "KEY", "MOOD", "ENERGY", "INSTRUMENTATION"]